version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0
  
jobs:
  integration-test-1:
    steps:
      - checkout
      - test-orb/greet
